CREATE TABLE dbo.Plot
(
	Id INT IDENTITY(1,1) 
		CONSTRAINT pk_Plot PRIMARY KEY CLUSTERED,
	DiscordServerId VARCHAR(50) NOT NULL,
	OwnerId NVARCHAR(100) NOT NULL,
	CenterX BIGINT NOT NULL,
	CenterY BIGINT NOT NULL,
	Area GEOMETRY NULL,
	RealmName NVARCHAR(100) NOT NULL,
	Notes NVARCHAR(500) NULL,
	NumberOfSides AS Area.STNumPoints() PERSISTED NOT NULL
);
GO

--CREATE SPATIAL INDEX siArea 
--	ON dbo.Plot (Area)
--	USING GEOMETRY_AUTO_GRID 
--	WITH
--	(
--		BOUNDING_BOX = (XMIN=-10000, YMIN=-10000, XMAX=10000, YMAX=10000)
--	);
--GO

CREATE NONCLUSTERED INDEX ixDiscordServerId_RealmName_INCLUDES
ON dbo.Plot (
                DiscordServerId,
                RealmName
            )
INCLUDE (Area, OwnerId, NumberOfSides);

CREATE TABLE dbo.AppLog
(
	Id INT IDENTITY(1,1) 
		CONSTRAINT pk_AppLog PRIMARY KEY CLUSTERED,
	LogTime DATETIME NOT NULL
		CONSTRAINT df_LogTime DEFAULT GETUTCDATE(),
	Message NVARCHAR(200) NOT NULL,
	StackTrace VARCHAR(MAX) NULL
);
GO

CREATE TABLE dbo.RealmSetting
(
	Id INT IDENTITY(1,1)
		CONSTRAINT pk_RealmSetting PRIMARY KEY CLUSTERED,
	[Key] VARCHAR(50)  NOT NULL,
	[Value] NVARCHAR(500) NOT NULL,
	DiscordServerId VARCHAR(40) NOT NULL,
	RealmName NVARCHAR(50) NOT NULL,
	PlayerId VARCHAR(40) NULL
);
GO

CREATE NONCLUSTERED INDEX ixDiscordServerId_RealmName_PlayerId 
	ON dbo.RealmSetting
	(
		[Key],
		DiscordServerId,
		RealmName,
		PlayerId
	) 
INCLUDE (Value);
GO

ALTER TABLE dbo.Plot
ADD StartTime DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
        DEFAULT GETUTCDATE() NOT NULL,
    EndTime DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
        DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999') NOT NULL,
    PERIOD FOR SYSTEM_TIME(StartTime, EndTime);


ALTER TABLE dbo.Plot SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE=dbo.PlotHistory));
GO